error inside the failure branch works: throw: wrong type to %s conversion
